adminUser:
  password: local:jx-demo/adminUser:password
  username: admin
docker:
  email: dummy
  password: local:jx-demo/docker:password
  url: https://535518648590.dkr.ecr.eu-west-1.amazonaws.com
  username: dummy
enableDocker: true
pipelineUser:
  email: iftachsc@cloudzone.io
  token: local:jx-demo/pipelineUser:token
  username: iftachsc
prow:
  hmacToken: local:jx-demo/prow:hmacToken
